site_name: ItsWA Online Documents
site_url: http://docs.itswa.xycode.club

repo_name: "XYCode-Kerman/ItsWA"
repo_url: "https://github.com/XYCode-Kerman/ItsWA"
edit_uri: "https://github.com/XYCode-Kerman/ItsWA"

nav:
  - 简介:
      - Getting Started: index.md
      - 开发路线图:
          - 0.0.3版本: intro/roadmaps/0.0.3.md
      - 关于 ItsWA: intro/about-itswa.md
  - 使用:
      - 安装: how-to-use/install.md
      - 初始化比赛: how-to-use/init-contest.md
      - 编辑题目: how-to-use/edit-problem.md
      - 开始评测: how-to-use/start-judge.md
  - 开发:
      - 开发规范: develop/rules.md

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

theme:
  name: material
  language: "zh"
  custom_dir: ./resources

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
