site_name: ItsWA Online Documents
site_url: http://docs.itswa.xycode.club

repo_name: "XYCode-Kerman/ItsWA"
repo_url: "https://github.com/XYCode-Kerman/ItsWA"
edit_uri: "https://github.com/XYCode-Kerman/ItsWA"

nav:
  - 简介:
      - Getting Started: index.md
      - 开发路线图:
          - 0.0.3版本: intro/roadmaps/0.0.3.md
      - 关于 ItsWA: intro/about-itswa.md
  - 使用:
      - 安装: how-to-use/install.md
      - 初始化比赛: how-to-use/init-contest.md
      - 编辑题目: how-to-use/edit-problem.md
      - 开始评测: how-to-use/start-judge.md
  - 开发:
      - 开发规范: develop/develop-format.md
      - 协作规范: develop/contribution-rules.md

markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - def_list
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

theme:
  name: material
  language: "zh"
  custom_dir: ./resources

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
