name: AutoFormat
on: [push, pull_request]

jobs:
  autoformat:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.10', '3.11', '3.12']

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install the project dependencies
        run: poetry install
      
      - name: Auto format
        run: bash autoformat.sh
      
      - name: Run flake8
        run: poetry run flake8 .
      
      - name: Run mypy
        run: poetry run mypy .
      
      - uses: actions-go/push@master
        # 不同的运行只推送一次
        if: ${{ matrix.os }} == 'ubuntu-latest' && ${{ matrix.python }} == '3.12'
        with:
          commit-message: 'style: 自动格式化代码'
          remote: origin